apiVersion: apps/v1
kind: Deployment
metadata:
  name: restarunnt-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restarunnt-management
  template:
    metadata:
      labels:
        app: restarunnt-management
    spec:
      containers:
      - name: restarunnt-management
        image: "h4ck3rd33p/restarunnt-management-flask-app"
        ports:
        - containerPort: 10000
        env:
        - name: NAME
          value: "World"
        - name: DATABASE_URL
          value: "sqlite:////app/instance/restaurant.db"

