apiVersion: v1
kind: Service
metadata:
  name: restarunnt-management
spec:
  type: LoadBalancer
  selector:
    app: restarunnt-management
  ports:
  - port: 80
    targetPort: 10000
    nodePort: 32436

